language: python
python:
  - "3.4"
  - "3.5"
  - "3.6"
  - "3.7"
  - "3.8"
matrix:
  include:
    - python: 2.7
      before_install:
        - pip install -U mock
        - pip install -U pytest
    - os: osx
      language: minimal
      before_install:
        - pip3 install -U pip
        - pip3 install -U pytest
# command to install dependencies
install:
  - pip install -r requirements.txt
# command to run tests
script:
  - pytest